import Head from "next/head";
import {
  Box,
  Button,
  Container,
  Group,
  Loader,
  Stack,
  Title,
} from "@mantine/core";

// See: https://github.com/konvajs/react-konva/issues/588
import { useEffect, useState } from "react";

export default function Home() {
  useEffect(() => {
    fetch("/api/generate").catch((e) => console.error(e));
    setIsLoading(false);
  }, []);
  const [isLoading, setIsLoading] = useState(true);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container mt={"100px"}>
        <Stack>
          <Title order={3}>Your Avatar</Title>
          <p>Refresh to regenerate the image!</p>
          <Box>
            {/* Use <img> instead of Next.js <Image> because Next.js has aggressive image caching that results in refreshes not working. */}
            <img alt={"Avatar"} src={"/image.png"} width={256} height={256} />
          </Box>
          {isLoading && <Loader />}
        </Stack>
      </Container>
    </>
  );
}
